package service

import (
	"archive/tar"
	"compress/gzip"
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"text/template"
	"time"

	"github.com/google/uuid"
	"github.com/mtpanel/mtpanel/internal/config"
	"github.com/mtpanel/mtpanel/internal/domain"
	"github.com/mtpanel/mtpanel/internal/infrastructure/systemd"
	"github.com/mtpanel/mtpanel/internal/repository"
)

const (
	telemtUnitName   = "telemt.service"
	telemtUnitPath   = "/etc/systemd/system/telemt.service"
	telemtConfigPath = "/etc/telemt/telemt.toml"
	tlsDomainDefault = "www.cloudflare.com"
)

var ErrProxyNotInstalled = errors.New("proxy is not installed")

var systemdUnitTmpl = template.Must(template.New("unit").Parse(`[Unit]
Description=TeleMT - Telegram MTProto Proxy
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
Group=root
ExecStart={{.BinPath}} {{.ConfigPath}}
Restart=on-failure
RestartSec=5
LimitNOFILE=65536
StandardOutput=journal
StandardError=journal
AmbientCapabilities=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
`))

var telemtConfigTmpl = template.Must(template.New("telemt.toml").Parse(`# Generated by MTPanel
[general]
log = "info"

[general.modes]
classic = true
secure = true
tls = true

[server]
bind = "0.0.0.0"
port = {{.Port}}
workers = {{.Workers}}

[access.users]
default = "{{.Secret}}"

[tls]
domain = "{{.TLSDomain}}"
`))

type unitData struct {
	BinPath    string
	ConfigPath string
}

type telemtConfigData struct {
	Port      int
	Workers   int
	Secret    string
	TLSDomain string
}

// ProxyService manages the TeleMT daemon lifecycle.
type ProxyService struct {
	cfg       *config.Config
	systemd   *systemd.Manager
	proxyRepo repository.ProxyConfigRepository
	linkRepo  repository.ProxyLinkRepository
	audit     repository.AuditRepository
	settings  repository.SettingsRepository
}

// NewProxyService creates a ProxyService.
func NewProxyService(
	cfg *config.Config,
	sm *systemd.Manager,
	proxyRepo repository.ProxyConfigRepository,
	linkRepo repository.ProxyLinkRepository,
	audit repository.AuditRepository,
	settings repository.SettingsRepository,
) *ProxyService {
	return &ProxyService{
		cfg:       cfg,
		systemd:   sm,
		proxyRepo: proxyRepo,
		linkRepo:  linkRepo,
		audit:     audit,
		settings:  settings,
	}
}

// Install downloads TeleMT, writes config + systemd unit, and enables the service.
func (s *ProxyService) Install(ctx context.Context) error {
	s.recordAudit(ctx, domain.AuditEventProxyInstall, "", "started install")

	if err := os.MkdirAll(filepath.Dir(s.cfg.MTProxyBinPath), 0o755); err != nil {
		return fmt.Errorf("proxy: create bin dir: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(telemtConfigPath), 0o750); err != nil {
		return fmt.Errorf("proxy: create config dir: %w", err)
	}

	downloadURL, err := telemtLatestAssetURL()
	if err != nil {
		return fmt.Errorf("proxy: resolve telemt asset: %w", err)
	}
	if err := downloadAndExtractTeleMT(ctx, downloadURL, s.cfg.MTProxyBinPath); err != nil {
		return fmt.Errorf("proxy: install telemt binary: %w", err)
	}

	secret := s.cfg.MTProxySecret
	if secret == "" {
		secret, err = generateSecret()
		if err != nil {
			return fmt.Errorf("proxy: generate secret: %w", err)
		}
	}

	proxyCfg := &domain.ProxyConfig{
		ID:      "default",
		Port:    s.cfg.MTProxyPort,
		Secret:  secret,
		Workers: 4,
		MaxConn: 60000,
	}
	if err := s.proxyRepo.Upsert(ctx, proxyCfg); err != nil {
		return fmt.Errorf("proxy: persist config: %w", err)
	}

	if err := s.writeTeleMTConfig(proxyCfg); err != nil {
		return fmt.Errorf("proxy: write telemt config: %w", err)
	}
	if err := s.writeSystemdUnit(); err != nil {
		return fmt.Errorf("proxy: write unit file: %w", err)
	}

	if err := s.systemd.DaemonReload(ctx); err != nil {
		return fmt.Errorf("proxy: daemon-reload: %w", err)
	}
	if err := s.systemd.EnableUnit(ctx, telemtUnitName); err != nil {
		return fmt.Errorf("proxy: enable unit: %w", err)
	}
	if err := s.systemd.StartUnit(ctx, telemtUnitName); err != nil {
		return fmt.Errorf("proxy: start unit: %w", err)
	}

	if err := s.settings.Set(ctx, "install_state", "installed"); err != nil {
		return fmt.Errorf("proxy: update install state: %w", err)
	}
	if err := s.settings.Set(ctx, "is_first_run", "false"); err != nil {
		return fmt.Errorf("proxy: update first_run: %w", err)
	}

	s.recordAudit(ctx, domain.AuditEventProxyInstall, "default", "install completed")
	return nil
}

// InstallWithPort updates runtime port before running install.
func (s *ProxyService) InstallWithPort(ctx context.Context, port int) error {
	if err := ValidatePort(port); err != nil {
		return err
	}
	s.cfg.MTProxyPort = port
	return s.Install(ctx)
}

// Start starts the TeleMT systemd unit.
func (s *ProxyService) Start(ctx context.Context) error {
	s.recordAudit(ctx, domain.AuditEventProxyStart, telemtUnitName, "")
	return s.systemd.StartUnit(ctx, telemtUnitName)
}

// Stop stops the TeleMT systemd unit.
func (s *ProxyService) Stop(ctx context.Context) error {
	s.recordAudit(ctx, domain.AuditEventProxyStop, telemtUnitName, "")
	return s.systemd.StopUnit(ctx, telemtUnitName)
}

// Restart restarts the TeleMT systemd unit.
func (s *ProxyService) Restart(ctx context.Context) error {
	s.recordAudit(ctx, domain.AuditEventProxyRestart, telemtUnitName, "")
	return s.systemd.RestartUnit(ctx, telemtUnitName)
}

// Status returns the current status of the proxy process.
func (s *ProxyService) Status(ctx context.Context) (domain.ProxyStatus, error) {
	unitStatus, err := s.systemd.GetUnitStatus(ctx, telemtUnitName)
	if err != nil {
		return domain.ProxyStatusUnknown, err
	}
	switch unitStatus {
	case systemd.UnitActive:
		return domain.ProxyStatusRunning, nil
	case systemd.UnitInactive:
		return domain.ProxyStatusStopped, nil
	case systemd.UnitFailed:
		return domain.ProxyStatusFailed, nil
	default:
		return domain.ProxyStatusUnknown, nil
	}
}

// GetSystemdUnit returns the systemd unit name for the proxy service.
func (s *ProxyService) GetSystemdUnit() string {
	return telemtUnitName
}

// RotateSecret generates a new secret, updates config, and restarts service.
func (s *ProxyService) RotateSecret(ctx context.Context) (string, error) {
	newSecret, err := generateSecret()
	if err != nil {
		return "", fmt.Errorf("proxy: generate secret: %w", err)
	}

	cfg, err := s.proxyRepo.GetActive(ctx)
	if err != nil {
		return "", fmt.Errorf("proxy: get active config: %w", err)
	}
	cfg.Secret = newSecret

	if err := s.proxyRepo.Upsert(ctx, cfg); err != nil {
		return "", fmt.Errorf("proxy: persist rotated secret: %w", err)
	}
	if err := s.writeTeleMTConfig(cfg); err != nil {
		return "", fmt.Errorf("proxy: rewrite config: %w", err)
	}
	if err := s.systemd.RestartUnit(ctx, telemtUnitName); err != nil {
		return "", fmt.Errorf("proxy: restart after secret rotate: %w", err)
	}

	s.recordAudit(ctx, domain.AuditEventSecretRotate, "default", "secret rotated")
	return newSecret, nil
}

// GenerateLink creates a new tg:// shareable proxy link.
func (s *ProxyService) GenerateLink(ctx context.Context, label string) (*domain.ProxyLink, error) {
	cfg, err := s.proxyRepo.GetActive(ctx)
	if err != nil {
		if isMissingProxyConfig(err) {
			return nil, ErrProxyNotInstalled
		}
		return nil, fmt.Errorf("proxy: no active config: %w", err)
	}

	host, err := publicIP(ctx)
	if err != nil {
		return nil, fmt.Errorf("proxy: detect public IP: %w", err)
	}

	id := uuid.New().String()
	tgLink := fmt.Sprintf("tg://proxy?server=%s&port=%d&secret=%s", host, cfg.Port, cfg.Secret)

	link := &domain.ProxyLink{
		ID:        id,
		Label:     label,
		Secret:    cfg.Secret,
		Host:      host,
		Port:      cfg.Port,
		Link:      tgLink,
		Active:    true,
		CreatedAt: time.Now().UTC(),
	}
	if err := s.linkRepo.Create(ctx, link); err != nil {
		return nil, fmt.Errorf("proxy: persist link: %w", err)
	}

	s.recordAudit(ctx, domain.AuditEventLinkCreate, id, label)
	return link, nil
}

// RevokeLink marks a proxy link as inactive.
func (s *ProxyService) RevokeLink(ctx context.Context, id string) error {
	if err := s.linkRepo.Revoke(ctx, id); err != nil {
		return fmt.Errorf("proxy: revoke link: %w", err)
	}
	s.recordAudit(ctx, domain.AuditEventLinkRevoke, id, "")
	return nil
}

// ListLinks returns all (or only active) proxy links.
func (s *ProxyService) ListLinks(ctx context.Context, activeOnly bool) ([]*domain.ProxyLink, error) {
	return s.linkRepo.List(ctx, activeOnly)
}

// GetLogs returns recent logs from the proxy systemd unit.
func (s *ProxyService) GetLogs(ctx context.Context, lines int) ([]string, error) {
	if lines <= 0 {
		lines = 100
	}
	logs, err := s.systemd.GetLogs(ctx, telemtUnitName, lines)
	if err != nil {
		if isMissingUnitLogs(err) {
			return []string{"TeleMT пока не установлен или сервис telemt.service не создан."}, nil
		}
		return nil, err
	}
	return logs, nil
}

// SetPort updates active proxy configuration and applies it immediately.
func (s *ProxyService) SetPort(ctx context.Context, port int) error {
	if err := ValidatePort(port); err != nil {
		return err
	}

	cfg, err := s.proxyRepo.GetActive(ctx)
	if err != nil {
		s.cfg.MTProxyPort = port
		return nil
	}

	cfg.Port = port
	if err := s.proxyRepo.Upsert(ctx, cfg); err != nil {
		return fmt.Errorf("proxy: persist port: %w", err)
	}
	if err := s.writeTeleMTConfig(cfg); err != nil {
		return fmt.Errorf("proxy: rewrite config: %w", err)
	}
	if err := s.systemd.RestartUnit(ctx, telemtUnitName); err != nil {
		return fmt.Errorf("proxy: restart after port update: %w", err)
	}

	s.cfg.MTProxyPort = port
	return nil
}

// ActiveConfig returns the latest persisted proxy configuration.
func (s *ProxyService) ActiveConfig(ctx context.Context) (*domain.ProxyConfig, error) {
	return s.proxyRepo.GetActive(ctx)
}

func (s *ProxyService) writeSystemdUnit() error {
	var buf strings.Builder
	if err := systemdUnitTmpl.Execute(&buf, unitData{
		BinPath:    s.cfg.MTProxyBinPath,
		ConfigPath: telemtConfigPath,
	}); err != nil {
		return err
	}
	return systemd.WriteUnitFile(telemtUnitPath, buf.String())
}

func (s *ProxyService) writeTeleMTConfig(cfg *domain.ProxyConfig) error {
	var buf strings.Builder
	if err := telemtConfigTmpl.Execute(&buf, telemtConfigData{
		Port:      cfg.Port,
		Workers:   cfg.Workers,
		Secret:    cfg.Secret,
		TLSDomain: tlsDomainDefault,
	}); err != nil {
		return err
	}
	return os.WriteFile(telemtConfigPath, []byte(buf.String()), 0o640)
}

func (s *ProxyService) recordAudit(ctx context.Context, et domain.AuditEventType, resID, detail string) {
	ev := &domain.AuditEvent{
		ID:         uuid.New().String(),
		EventType:  et,
		ActorID:    "system",
		ResourceID: resID,
		Detail:     detail,
		CreatedAt:  time.Now().UTC(),
	}
	_ = s.audit.Record(ctx, ev)
}

func generateSecret() (string, error) {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

func telemtAssetName() (string, error) {
	arch := ""
	switch runtime.GOARCH {
	case "amd64":
		arch = "x86_64"
	case "arm64":
		arch = "aarch64"
	default:
		return "", fmt.Errorf("unsupported architecture %s", runtime.GOARCH)
	}

	libc := "gnu"
	if isMuslLinux() {
		libc = "musl"
	}

	return fmt.Sprintf("telemt-%s-linux-%s.tar.gz", arch, libc), nil
}

func telemtLatestAssetURL() (string, error) {
	asset, err := telemtAssetName()
	if err != nil {
		return "", err
	}
	return "https://github.com/telemt/telemt/releases/latest/download/" + asset, nil
}

func isMuslLinux() bool {
	if runtime.GOOS != "linux" {
		return false
	}
	if _, err := os.Stat("/etc/alpine-release"); err == nil {
		return true
	}
	matches, _ := filepath.Glob("/lib/ld-musl-*.so.*")
	if len(matches) > 0 {
		return true
	}
	matches64, _ := filepath.Glob("/lib64/ld-musl-*.so.*")
	return len(matches64) > 0
}

func downloadBinary(ctx context.Context, url, dest string) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return err
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("HTTP %d fetching %s", resp.StatusCode, url)
	}

	tmp := dest + ".tmp"
	f, err := os.OpenFile(tmp, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o755)
	if err != nil {
		return err
	}
	if _, err := io.Copy(f, resp.Body); err != nil {
		f.Close()
		_ = os.Remove(tmp)
		return err
	}
	if err := f.Close(); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return os.Rename(tmp, dest)
}

func downloadAndExtractTeleMT(ctx context.Context, url, dest string) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return err
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("HTTP %d fetching %s", resp.StatusCode, url)
	}

	gz, err := gzip.NewReader(resp.Body)
	if err != nil {
		return fmt.Errorf("open gzip stream: %w", err)
	}
	defer gz.Close()

	tr := tar.NewReader(gz)
	tmp := dest + ".tmp"
	found := false

	for {
		hdr, err := tr.Next()
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return fmt.Errorf("read tar entry: %w", err)
		}
		if hdr.Typeflag != tar.TypeReg {
			continue
		}

		name := filepath.Base(hdr.Name)
		if name != "telemt" {
			continue
		}

		if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
			return err
		}
		out, err := os.OpenFile(tmp, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o755)
		if err != nil {
			return err
		}
		if _, err := io.Copy(out, tr); err != nil {
			out.Close()
			_ = os.Remove(tmp)
			return err
		}
		if err := out.Close(); err != nil {
			_ = os.Remove(tmp)
			return err
		}
		found = true
		break
	}

	if !found {
		return fmt.Errorf("binary telemt not found inside archive")
	}
	return os.Rename(tmp, dest)
}

func publicIP(ctx context.Context) (string, error) {
	services := []string{
		"https://api4.my-ip.io/ip",
		"https://ipv4.icanhazip.com",
		"https://api.ipify.org",
	}
	for _, svc := range services {
		req, err := http.NewRequestWithContext(ctx, http.MethodGet, svc, nil)
		if err != nil {
			continue
		}
		resp, err := (&http.Client{Timeout: 5 * time.Second}).Do(req)
		if err != nil {
			continue
		}
		b, err := io.ReadAll(io.LimitReader(resp.Body, 64))
		resp.Body.Close()
		if err != nil {
			continue
		}
		ip := strings.TrimSpace(string(b))
		if ip != "" {
			return ip, nil
		}
	}
	return "", fmt.Errorf("could not detect public IP")
}

// mtproxyVersion is preserved for compatibility with existing callsites.
func mtproxyVersion(binPath string) string {
	out, err := exec.Command(binPath, "--version").Output()
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(out))
}

func isMissingProxyConfig(err error) bool {
	if err == nil {
		return false
	}
	msg := strings.ToLower(err.Error())
	return strings.Contains(msg, "proxy config not found")
}

func isMissingUnitLogs(err error) bool {
	if err == nil {
		return false
	}
	msg := strings.ToLower(err.Error())
	return strings.Contains(msg, "no such file") ||
		strings.Contains(msg, "unit telemt.service could not be found") ||
		strings.Contains(msg, "no journal files were found")
}
